sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t mamri/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mamri/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker-react'
  env: 'Dockerreact-env'
  bucket_name: 'elasticbeanstalk-us-east-2-372842733467'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY
    
